spring.application.name=corebank
spring.datasource.url=jdbc:mysql://localhost:3306/corebank?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
app.jwt.secret=change_me_to_a_long_random_secret
app.jwt.expiration-ms=86400000
